In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [37]:
from sklearn.datasets import load_breast_cancer
bc = load_breast_cancer()
dir(bc)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [38]:
df = pd.DataFrame(
    bc['data'], columns = bc['feature_names']
)
df['target'] = bc['target']
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension   ...    worst texture  worst perimeter  worst area  \
0                 0.07871   ...            17.33           184.60      2019.0   
1                 0.05667   ...            23.41           158.80      1956.0   
2                 0.05999   ...            25.53           152.50      1709.0   
3                 0.09744   ...            26.50            98.87       567.7   
4                 0.05883   ...            16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [39]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [40]:
# df.corr()
# df.corr()['target']
# df.corr()['target'][df.corr()['target'] < -0.5].index

print(len(np.array(df.corr()['target'][df.corr()['target'] < -0.5].index)))
np.array(df.corr()['target'][df.corr()['target'] < -0.5].index)

15


array(['mean radius', 'mean perimeter', 'mean area', 'mean compactness',
       'mean concavity', 'mean concave points', 'radius error',
       'perimeter error', 'area error', 'worst radius', 'worst perimeter',
       'worst area', 'worst compactness', 'worst concavity',
       'worst concave points'], dtype=object)

In [43]:
i = np.array(df.corr()['target'][df.corr()['target'] < -0.5].index)
dfNew = df[i]
dfNew['target'] = df['target']
dfNew.head()

c:\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


mean radius  mean perimeter  mean area  mean compactness  mean concavity  \
0        17.99          122.80     1001.0           0.27760          0.3001   
1        20.57          132.90     1326.0           0.07864          0.0869   
2        19.69          130.00     1203.0           0.15990          0.1974   
3        11.42           77.58      386.1           0.28390          0.2414   
4        20.29          135.10     1297.0           0.13280          0.1980   

   mean concave points  radius error  perimeter error  area error  \
0              0.14710        1.0950            8.589      153.40   
1              0.07017        0.5435            3.398       74.08   
2              0.12790        0.7456            4.585       94.03   
3              0.10520        0.4956            3.445       27.23   
4              0.10430        0.7572            5.438       94.44   

   worst radius  worst perimeter  worst area  worst compactness  \
0         25.38           184.60      2019.0             0.6656   
1         24.99           158.80      1956.0             0.1866   
2         23.57           152.50      1709.0             0.4245   
3         14.91            98.87       567.7             0.8663   
4         22.54           152.20      1575.0             0.2050   

   worst concavity  worst concave points  target  
0           0.7119                0.2654       0  
1           0.2416                0.1860       0  
2           0.4504                0.2430       0  
3           0.6869                0.2575       0  
4           0.4000                0.1625       0

### Standard Scaler

In [77]:
from sklearn.preprocessing import StandardScaler
stdscaler = StandardScaler()

# target tidak diikutsertakan
datastd = stdscaler.fit_transform(dfNew.iloc[:,:-1])
datastd[0]

array([1.09706398, 1.26993369, 0.9843749 , 3.28351467, 2.65287398,
       2.53247522, 2.48973393, 2.83303087, 2.48757756, 1.88668963,
       2.30360062, 2.00123749, 2.61666502, 2.10952635, 2.29607613])

In [110]:
# Check outlier, -2.5 < z-score > 2.5
dfZscore = pd.DataFrame(datastd)
dfZscore.head()

# mempertemukan kembali features & target
dfZscore['target'] = dfNew['target']
dfZscore.head()

0         1         2         3         4         5         6  \
0  1.829821  1.685955  1.908708 -0.487072 -0.023846  0.548144  0.499255   
1  1.579888  1.566503  1.558884  1.052926  1.363478  2.037231  1.228676   
2  1.750297  1.776573  1.826229  0.539340  1.371011  1.428493  1.270543   
3 -0.476375 -0.387148 -0.505650  1.244335  0.866302  0.824656 -0.255070   
4  1.170908  1.138125  1.095295  0.088295  0.300072  0.646935  0.149883   

          7         8         9        10        11        12        13  \
0  0.263327  0.742402  1.805927  1.535126  1.890489 -0.430444 -0.146749   
1  0.850928  1.181336  1.511870  1.347475  1.456285  1.082932  0.854974   
2  1.273189  1.190357  1.298575  1.338539  1.220724 -0.313395  0.613179   
3 -0.321304 -0.289258 -0.165498 -0.115009 -0.244320  1.721616  1.263243   
4  0.155410  0.298627  1.368983  1.368325  1.275220  0.021215  0.509552   

         14  target  
0  1.087084       0  
1  1.955000       0  
2  0.729259       0  
3  0.905888       0  
4  1.196716       0

In [113]:
# hapus outlier: -2.5 < z-score > 2.5
dfZscore[(dfZscore < -2.5) | (dfZscore > 2.5)] = np.NaN
dfZscore = dfZscore.dropna()
dfZscore.head()

0         1         2         3         4         5         6  \
0  1.829821  1.685955  1.908708 -0.487072 -0.023846  0.548144  0.499255   
1  1.579888  1.566503  1.558884  1.052926  1.363478  2.037231  1.228676   
2  1.750297  1.776573  1.826229  0.539340  1.371011  1.428493  1.270543   
3 -0.476375 -0.387148 -0.505650  1.244335  0.866302  0.824656 -0.255070   
4  1.170908  1.138125  1.095295  0.088295  0.300072  0.646935  0.149883   

          7         8         9        10        11        12        13  \
0  0.263327  0.742402  1.805927  1.535126  1.890489 -0.430444 -0.146749   
1  0.850928  1.181336  1.511870  1.347475  1.456285  1.082932  0.854974   
2  1.273189  1.190357  1.298575  1.338539  1.220724 -0.313395  0.613179   
3 -0.321304 -0.289258 -0.165498 -0.115009 -0.244320  1.721616  1.263243   
4  0.155410  0.298627  1.368983  1.368325  1.275220  0.021215  0.509552   

         14  target  
0  1.087084       0  
1  1.955000       0  
2  0.729259       0  
3  0.905888       0  
4  1.196716       0

In [119]:
datastd = np.array(dfZscore.iloc[:, :-1])
datastd[0]

array([ 1.82982061,  1.68595471,  1.90870825, -0.48707167, -0.02384586,
        0.54814416,  0.4992546 ,  0.26332697,  0.74240195,  1.80592744,
        1.53512599,  1.89048899, -0.43044422, -0.14674897,  1.0870843 ])

### PCA

In [120]:
from sklearn import decomposition
pca = decomposition.PCA(n_components = 3)

datapca = pca.fit_transform(datastd)
datapca[0]

array([ 4.24293416, -2.66952123, -0.86054826])

In [121]:
pca.n_components_

3

In [122]:
pca.explained_variance_ratio_

array([0.7473689 , 0.14043917, 0.06210436])

In [123]:
# inverse ke value semula
stdscaler.inverse_transform(pca.inverse_transform(datapca[0]))

array([2.12198224e+01, 1.37840634e+02, 1.28890297e+03, 7.71349988e-02,
       9.93118141e-02, 7.51320765e-02, 5.36483275e-01, 3.52483702e+00,
       7.04583762e+01, 2.49491051e+01, 1.62610221e+02, 1.76340800e+03,
       1.90055577e-01, 2.73401849e-01, 1.57459386e-01])

<hr>

### Pipeline: Standard Scaler + PCA

In [72]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(
    StandardScaler(),
    decomposition.PCA(n_components = 3)
)
stdpca = pipe.fit_transform(dfNew.iloc[:,:-1])
stdpca[0]

array([ 8.29601665, -1.61286602,  2.2463328 ])

In [73]:
# inverse ke value semula
pipe.inverse_transform(stdpca)[0]

array([1.89361465e+01, 1.29256168e+02, 1.18788294e+03, 2.60684046e-01,
       3.21696506e-01, 1.48732685e-01, 1.13852282e+00, 8.48284503e+00,
       1.49727446e+02, 2.37476708e+01, 1.65455426e+02, 1.80523551e+03,
       6.34443510e-01, 7.90349764e-01, 2.67061632e-01])

<hr>

### Splitting datasets

In [135]:
x = datapca
y = np.array(dfZscore['target'])
print(x.shape, y.shape)

(516, 3) (516,)


In [136]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(
    x, y, test_size = .15
)
print(xtr.shape, xts.shape)
print(ytr.shape, yts.shape)

(438, 3) (78, 3)
(438,) (78,)


### K-Nearest Neighbors

In [139]:
from sklearn.neighbors import KNeighborsClassifier
k = round(xtr.shape[0] ** .5)
k

21

In [140]:
model = KNeighborsClassifier(n_neighbors = k)
model.fit(xtr, ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

### Evaluation Metrics

In [143]:
from sklearn.metrics import classification_report

print(classification_report(yts, model.predict(xts)))

              precision    recall  f1-score   support

           0       0.46      0.22      0.30        27
           1       0.68      0.86      0.76        51

    accuracy                           0.64        78
   macro avg       0.57      0.54      0.53        78
weighted avg       0.60      0.64      0.60        78

