<img src="https://scikit-learn.org/stable/_images/grid_search_workflow.png" width="70%"/>

In [1]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

### Cross validation

- split dataset: train set & test set
- train set split: train set & validation set: A B C
    - model train AB, validate C => score
    - model train AC, validate B => score
    - model train CB, validate A => score
    - rata2 score = ?

<img src="https://scikit-learn.org/stable/_images/grid_search_cross_validation.png" height="70%"/>

### K-Fold Cross Validation

In [2]:
x = [1,2,3,4,5,6,7,8,9]
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)

In [3]:
# 1,2,3,4,5,6,7,8,9
# 1 2 3 4 5 6 7 8 9
# [4 5 6 7  8 9]  [1 2 3]
for i, j in kf.split(x):
    print(i, j)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
import numpy as np
import pandas as pd
df = pd.DataFrame(iris['data'], columns=['SL','SW','PL','PW'])
df['target'] = iris['target']
# df.head()

In [6]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(
    df[['SL','SW','PL','PW']],
    df['target'],
    test_size = .1
)

In [7]:
dfTr = pd.concat([xtr, ytr], axis=1)
dfTs = pd.concat([xts, yts], axis=1)

In [8]:
def hitungScore(model, xtr, xts, ytr, yts):
    model.fit(xtr, ytr)
    return model.score(xts, yts)

In [10]:
score = []
kf = KFold(n_splits=5)
for i, j in kf.split(np.array(dfTr)):
    # print(i, j)   # i = index train, j = index validation
    # print(dfTr.iloc[i])
    xtrcv = dfTr.iloc[i][['SL', 'SW', 'PL', 'PW']]
    ytrcv = dfTr.iloc[i]['target']
    xvalcv = dfTr.iloc[j][['SL', 'SW', 'PL', 'PW']]
    yvalcv = dfTr.iloc[j]['target']
    score.append(
        hitungScore(
            LogisticRegression(), xtrcv, xvalcv, ytrcv, yvalcv))

score
# dfTr = 135 => 5 fold => 27
# training = 27 + 27 + 27 + 27 =    validation = 27

C:\Users\lintangwisesa\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\lintangwisesa\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

[1.0,
 0.9259259259259259,
 0.9629629629629629,
 0.9629629629629629,
 0.9259259259259259]

In [11]:
np.mean(score)

0.9555555555555555

In [14]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(
    LogisticRegression(), dfTr[['SL', 'SW', 'PL', 'PW']], dfTr['target'], cv=5)
)

print(np.mean(cross_val_score(
    LogisticRegression(), dfTr[['SL', 'SW', 'PL', 'PW']], dfTr['target'], cv=5)
))

[1.         0.88888889 0.96296296 1.         0.92592593]
0.9555555555555555


C:\Users\lintangwisesa\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\lintangwisesa\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h