# Cross Validation

<hr>

### Best practices:

- Split dataset: training set & testing set
- Split training set: training set & validation set
- Misal training set displit 3: A B C, maka: 
    - model di train dengan AB lalu divalidate dengan C
    - model di train dengan AC lalu divalidate dengan B
    - model di train dengan BC lalu divalidate dengan A
- Dari situ didapatkan score masing2 CV (crossval), ambil rata2 untuk evaluasi model.


<img src="https://scikit-learn.org/stable/_images/grid_search_workflow.png" width="50%" height="50%"/>

<hr>

### Hyperparameter Tuning

- Selama dilakukan cross validation, dapat sekaligus dicari nilai hyperparameter terbaik.
- Hasilnya digunakan pada model final & digunakan untuk predict testing set.

<img src="https://scikit-learn.org/stable/_images/grid_search_cross_validation.png" width="50%" height="50%"/>


In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [43]:
iris = load_iris()

df = pd.DataFrame(iris['data'], columns=['SL','SW','PL','PW'])
df['target'] = iris['target']
df.head()

SL   SW   PL   PW  target
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [46]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(
    df[['SL','SW','PL','PW']], df['target']
)
xtr.head()

SL   SW   PL   PW
147  6.5  3.0  5.2  2.0
14   5.8  4.0  1.2  0.2
129  7.2  3.0  5.8  1.6
62   6.0  2.2  4.0  1.0
134  6.1  2.6  5.6  1.4

<hr>

# 1. K-Fold Cross Validation

In [51]:
from sklearn.model_selection import KFold
# kf = KFold(n_splits=3) # jumlah 'lipatan', max = jumlah sample
kf = KFold(n_splits=9)

In [52]:
x = [1,2,3,4,5,6,7,8,9]
for train, validate in kf.split(x):
    print(train, validate)

# train: data utk train
# validate: data utk validate

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]
